In [5]:
import pandas as pd
import math
import matplotlib.pyplot as plt

In [179]:
df = pd.read_csv(r'C:\Users\wiley\OneDrive\Desktop\NBA_Repo\csv\common_player_info.csv')
df.head()

,person_id,first_name,last_name,display_first_last,display_last_comma_first,display_fi_last,player_slug,birthdate,school,country,...,playercode,from_year,to_year,dleague_flag,nba_flag,games_played_flag,draft_year,draft_round,draft_number,greatest_75_flag
0,76001,Alaa,Abdelnaby,Alaa Abdelnaby,"Abdelnaby, Alaa",A. Abdelnaby,alaa-abdelnaby,1968-06-24 00:00:00,Duke,USA,...,HISTADD_alaa_abdelnaby,1990.0,1994.0,N,Y,Y,1990,1,25,N
1,76003,Kareem,Abdul-Jabbar,Kareem Abdul-Jabbar,"Abdul-Jabbar, Kareem",K. Abdul-Jabbar,kareem-abdul-jabbar,1947-04-16 00:00:00,UCLA,USA,...,HISTADD_kareem_abdul-jabbar,1969.0,1988.0,N,Y,Y,1969,1,1,Y
2,1505,Tariq,Abdul-Wahad,Tariq Abdul-Wahad,"Abdul-Wahad, Tariq",T. Abdul-Wahad,tariq-abdul-wahad,1974-11-03 00:00:00,San Jose State,France,...,tariq_abdul-wahad,1997.0,2003.0,N,Y,Y,1997,1,11,N
3,949,Shareef,Abdur-Rahim,Shareef Abdur-Rahim,"Abdur-Rahim, Shareef",S. Abdur-Rahim,shareef-abdur-rahim,1976-12-11 00:00:00,California,USA,...,shareef_abdur-rahim,1996.0,2007.0,N,Y,Y,1996,1,3,N
4,76005,Tom,Abernethy,Tom Abernethy,"Abernethy, Tom",T. Abernethy,tom-abernethy,1954-05-06 00:00:00,Indiana,USA,...,HISTADD_tom_abernethy,1976.0,1980.0,N,Y,Y,1976,3,43,N

In [183]:
df["year_in_league"] = df["to_year"] - df["from_year"]

In [185]:
print(df.values)
print(df.columns)
print(df.index)

[[76001 'Alaa' 'Abdelnaby' ... '25' 'N' 4.0]
 [76003 'Kareem' 'Abdul-Jabbar' ... '1' 'Y' 19.0]
 [1505 'Tariq' 'Abdul-Wahad' ... '11' 'N' 6.0]
 ...
 [78647 'Jim' 'Zoet' ... 'Undrafted' 'N' 0.0]
 [1627826 'Ivica' 'Zubac' ... '32' 'N' 7.0]
 [78650 'Matt' 'Zunic' ... nan 'N' 0.0]]
Index(['person_id', 'first_name', 'last_name', 'display_first_last',
       'display_last_comma_first', 'display_fi_last', 'player_slug',
       'birthdate', 'school', 'country', 'last_affiliation', 'height',
       'weight', 'season_exp', 'jersey', 'position', 'rosterstatus',
       'games_played_current_season_flag', 'team_id', 'team_name',
       'team_abbreviation', 'team_code', 'team_city', 'playercode',
       'from_year', 'to_year', 'dleague_flag', 'nba_flag', 'games_played_flag',
       'draft_year', 'draft_round', 'draft_number', 'greatest_75_flag',
       'year_in_league'],
      dtype='object')
RangeIndex(start=0, stop=4171, step=1)

In [187]:
name_school = df[["display_last_comma_first","school"]]
name_school.dropna()

     display_last_comma_first             school
0             Abdelnaby, Alaa               Duke
1        Abdul-Jabbar, Kareem               UCLA
2          Abdul-Wahad, Tariq     San Jose State
3        Abdur-Rahim, Shareef         California
4              Abernethy, Tom            Indiana
...                       ...                ...
4166             Zipser, Paul      Bayern Munich
4167              Zizic, Ante        Darussafaka
4168                Zoet, Jim         Kent State
4169             Zubac, Ivica        Mega Basket
4170              Zunic, Matt  George Washington

[4156 rows x 2 columns]

In [238]:
df[df["school"] == "Tennessee"]

,person_id,first_name,last_name,display_first_last,display_last_comma_first,display_fi_last,player_slug,birthdate,school,country,...,from_year,to_year,dleague_flag,nba_flag,games_played_flag,draft_year,draft_round,draft_number,greatest_75_flag,year_in_league
45,1629734,Kyle,Alexander,Kyle Alexander,"Alexander, Kyle",K. Alexander,kyle-alexander,1996-10-21 00:00:00,Tennessee,Canada,...,2019.0,2019.0,Y,Y,Y,Undrafted,Undrafted,Undrafted,N,0.0
352,1629648,Jordan,Bone,Jordan Bone,"Bone, Jordan",J. Bone,jordan-bone,1997-11-05 00:00:00,Tennessee,USA,...,2019.0,2020.0,Y,Y,Y,2019,2,57,N,1.0
534,76311,Art,Burris,Art Burris,"Burris, Art",A. Burris,art-burris,1924-04-07 00:00:00,Tennessee,USA,...,1950.0,1951.0,N,Y,Y,1950,3,NaN,N,1.0
639,1631113,Kennedy,Chandler,Kennedy Chandler,"Chandler, Kennedy",K. Chandler,kennedy-chandler,2002-09-16 00:00:00,Tennessee,USA,...,2022.0,2022.0,Y,Y,Y,2022,2,38,N,0.0
786,76475,Terry,Crosby,Terry Crosby,"Crosby, Terry",T. Crosby,terry-crosby,1957-01-04 00:00:00,Tennessee,USA,...,1979.0,1979.0,N,Y,Y,1979,3,62,N,0.0
1061,107,Dale,Ellis,Dale Ellis,"Ellis, Dale",D. Ellis,dale-ellis,1960-08-06 00:00:00,Tennessee,USA,...,1983.0,1999.0,N,Y,Y,1983,1,9,N,16.0
1437,76899,Ernie,Grunfeld,Ernie Grunfeld,"Grunfeld, Ernie",E. Grunfeld,ernie-grunfeld,1955-04-24 00:00:00,Tennessee,USA,...,1977.0,1985.0,N,Y,Y,1977,1,11,N,8.0
1462,2409,Marcus,Haislip,Marcus Haislip,"Haislip, Marcus",M. Haislip,marcus-haislip,1980-12-22 00:00:00,Tennessee,USA,...,2002.0,2009.0,N,Y,Y,2002,1,13,N,7.0
1475,984,Steve,Hamer,Steve Hamer,"Hamer, Steve",S. Hamer,steve-hamer,1973-11-13 00:00:00,Tennessee,USA,...,1996.0,1996.0,N,Y,Y,1996,2,38,N,0.0
1543,202699,Tobias,Harris,Tobias Harris,"Harris, Tobias",T. Harris,tobias-harris,1992-07-15 00:00:00,Tennessee,USA,...,2011.0,2023.0,N,Y,Y,2011,1,19,N,12.0
1569,76974,Marshall,Hawkins,Marshall Hawkins,"Hawkins, Marshall",M. Hawkins,marshall-hawkins,1924-08-03 00:00:00,Tennessee,USA,...,1949.0,1949.0,N,Y,Y,1948,NaN,NaN,N,0.0
1668,77037,Bob,Hogsett,Bob Hogsett,"Hogsett, Bob",B. Hogsett,bob-hogsett,1941-01-29 00:00:00,Tennessee,USA,...,1966.0,1966.0,N,Y,Y,Undrafted,Undrafted,Undrafted,N,0.0
1694,203816,Scotty,Hopson,Scotty Hopson,"Hopson, Scotty",S. Hopson,scotty-hopson,1989-08-08 00:00:00,Tennessee,USA,...,2013.0,2021.0,Y,Y,Y,2011,0,0,N,8.0
1707,275,Allan,Houston,Allan Houston,"Houston, Allan",A. Houston,allan-houston,1971-04-20 00:00:00,Tennessee,USA,...,1993.0,2004.0,N,Y,Y,1993,1,11,N,11.0
1882,1630553,Keon,Johnson,Keon Johnson,"Johnson, Keon",K. Johnson,keon-johnson,2002-03-10 00:00:00,Tennessee,USA,...,2021.0,2023.0,Y,Y,Y,2021,1,21,N,2.0
1895,77163,Reggie,Johnson,Reggie Johnson,"Johnson, Reggie",R. Johnson,reggie-johnson,1957-06-25 00:00:00,Tennessee,USA,...,1980.0,1983.0,N,Y,Y,1980,1,15,N,3.0
2042,77264,Bernard,King,Bernard King,"King, Bernard",B. King,bernard-king,1956-12-04 00:00:00,Tennessee,USA,...,1977.0,1992.0,N,Y,Y,1977,1,7,N,15.0
2090,77302,Len,Kosmalski,Len Kosmalski,"Kosmalski, Len",L. Kosmalski,len-kosmalski,1951-11-29 00:00:00,Tennessee,USA,...,1974.0,1975.0,N,Y,Y,1974,2,24,N,1.0
2240,1100,Ian,Lockhart,Ian Lockhart,"Lockhart, Ian",I. Lockhart,ian-lockhart,1967-06-25 00:00:00,Tennessee,USA,...,1990.0,1990.0,N,Y,Y,Undrafted,Undrafted,Undrafted,N,0.0
2494,203895,Jordan,McRae,Jordan McRae,"McRae, Jordan",J. McRae,jordan-mcrae,1991-03-28 00:00:00,Tennessee,USA,...,2015.0,2019.0,Y,Y,Y,2014,2,58,N,4.0
2501,77572,Dick,Mehen,Dick Mehen,"Mehen, Dick",D. Mehen,dick-mehen,1922-05-20 00:00:00,Tennessee,USA,...,1949.0,1951.0,N,Y,Y,Undrafted,Undrafted,Undrafted,N,2.0
2731,77720,Dyron,Nix,Dyron Nix,"Nix, Dyron",D. Nix,dyron-nix,1967-02-11 00:00:00,Tennessee,USA,...,1989.0,1989.0,N,Y,Y,1989,2,29,N,0.0
2780,77774,Garland,O'Shields,Garland O'Shields,"O'Shields, Garland",G. O'Shields,garland-oshields,1921-05-23 00:00:00,Tennessee,USA,...,1946.0,1946.0,N,Y,Y,Undrafted,Undrafted,Undrafted,N,0.0
2981,1630582,Yves,Pons,Yves Pons,"Pons, Yves",Y. Pons,yves-pons,1999-05-07 00:00:00,Tennessee,France,...,2021.0,2021.0,Y,Y,Y,Undrafted,Undrafted,Undrafted,N,0.0
3109,1626196,Josh,Richardson,Josh Richardson,"Richardson, Josh",J. Richardson,josh-richardson,1993-09-15 00:00:00,Tennessee,USA,...,2015.0,2023.0,Y,Y,Y,2015,2,40,N,8.0
3203,78021,Doug,Roth,Doug Roth,"Roth, Doug",D. Roth,doug-roth,1967-08-24 00:00:00,Tennessee,USA,...,1989.0,1989.0,N,Y,Y,1989,2,41,N,0.0
3292,1629678,Admiral,Schofield,Admiral Schofield,"Schofield, Admiral",A. Schofield,admiral-schofield,1997-03-30 00:00:00,Tennessee,United Kingdom,...,2019.0,2023.0,Y,Y,Y,2019,2,42,N,4.0
3506,1630531,Jaden,Springer,Jaden Springer,"Springer, Jaden",J. Springer,jaden-springer,2002-09-25 00:00:00,Tennessee,USA,...,2021.0,2023.0,Y,Y,Y,2021,1,28,N,2.0
3542,203950,Jarnell,Stokes,Jarnell Stokes,"Stokes, Jarnell",J. Stokes,jarnell-stokes,1994-01-07 00:00:00,Tennessee,USA,...,2014.0,2016.0,Y,Y,Y,2014,2,35,N,2.0
3883,201228,C.J.,Watson,C.J. Watson,"Watson, C.J.",C. Watson,cj-watson,1984-04-17 00:00:00,Tennessee,USA,...,2007.0,2016.0,Y,Y,Y,Undrafted,Undrafted,Undrafted,N,9.0
3949,78514,Tony,White,Tony White,"White, Tony",T. White,tony-white,1965-02-15 00:00:00,Tennessee,USA,...,1987.0,1987.0,N,Y,Y,1987,2,33,N,0.0
4008,1629684,Grant,Williams,Grant Williams,"Williams, Grant",G. Williams,grant-williams,1998-11-30 00:00:00,Tennessee,USA,...,2019.0,2023.0,N,Y,Y,2019,1,22,N,4.0
4138,2428,Vincent,Yarbrough,Vincent Yarbrough,"Yarbrough, Vincent",V. Yarbrough,vincent-yarbrough,1981-03-21 00:00:00,Tennessee,USA,...,2002.0,2002.0,N,Y,Y,2002,2,32,N,0.0

In [240]:
schools = ["Tennessee","Alabama","Georgia","South Carolina","Kentucky","Mississippi State", "Mississippi","Vanderbilt","Auburn","Louisiana State","Florida","Arkansas","Missouri"]

In [242]:
sec_df = df[df["school"].isin(schools)]
sec_df

,person_id,first_name,last_name,display_first_last,display_last_comma_first,display_fi_last,player_slug,birthdate,school,country,...,from_year,to_year,dleague_flag,nba_flag,games_played_flag,draft_year,draft_round,draft_number,greatest_75_flag,year_in_league
22,1628389,Bam,Adebayo,Bam Adebayo,"Adebayo, Bam",B. Adebayo,bam-adebayo,1997-07-18 00:00:00,Kentucky,USA,...,2017.0,2023.0,N,Y,Y,2017,1,14,N,6.0
45,1629734,Kyle,Alexander,Kyle Alexander,"Alexander, Kyle",K. Alexander,kyle-alexander,1996-10-21 00:00:00,Tennessee,Canada,...,2019.0,2019.0,Y,Y,Y,Undrafted,Undrafted,Undrafted,N,0.0
74,1507,Derek,Anderson,Derek Anderson,"Anderson, Derek",D. Anderson,derek-anderson,1974-07-18 00:00:00,Kentucky,USA,...,1997.0,2007.0,N,Y,Y,1997,1,13,N,10.0
82,76041,Kim,Anderson,Kim Anderson,"Anderson, Kim",K. Anderson,kim-anderson,1955-05-12 00:00:00,Missouri,USA,...,1978.0,1978.0,N,Y,Y,1978,7,146,N,0.0
90,1000,Shandon,Anderson,Shandon Anderson,"Anderson, Shandon",S. Anderson,shandon-anderson,1973-12-31 00:00:00,Georgia,USA,...,1996.0,2005.0,N,Y,Y,1996,2,54,N,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4071,78582,Nikita,Wilson,Nikita Wilson,"Wilson, Nikita",N. Wilson,nikita-wilson,1964-02-25 00:00:00,Louisiana State,USA,...,1987.0,1987.0,N,Y,Y,1987,2,30,N,0.0
4090,78600,Brian,Winters,Brian Winters,"Winters, Brian",B. Winters,brian-winters,1952-03-01 00:00:00,South Carolina,USA,...,1974.0,1982.0,N,Y,Y,1974,1,12,N,8.0
4106,1630218,Robert,Woodard II,Robert Woodard II,"Woodard II, Robert",R. Woodard II,robert-woodard-ii,1999-09-22 00:00:00,Mississippi State,USA,...,2020.0,2021.0,Y,Y,Y,2020,2,40,N,1.0
4138,2428,Vincent,Yarbrough,Vincent Yarbrough,"Yarbrough, Vincent",V. Yarbrough,vincent-yarbrough,1981-03-21 00:00:00,Tennessee,USA,...,2002.0,2002.0,N,Y,Y,2002,2,32,N,0.0
4164,2583,Derrick,Zimmerman,Derrick Zimmerman,"Zimmerman, Derrick",D. Zimmerman,derrick-zimmerman,1981-12-02 00:00:00,Mississippi State,USA,...,2005.0,2005.0,Y,Y,Y,2003,2,40,N,0.0

In [244]:
sec_df.sort_values(["year_in_league"], ascending = [False])
sec_df

,person_id,first_name,last_name,display_first_last,display_last_comma_first,display_fi_last,player_slug,birthdate,school,country,...,from_year,to_year,dleague_flag,nba_flag,games_played_flag,draft_year,draft_round,draft_number,greatest_75_flag,year_in_league
22,1628389,Bam,Adebayo,Bam Adebayo,"Adebayo, Bam",B. Adebayo,bam-adebayo,1997-07-18 00:00:00,Kentucky,USA,...,2017.0,2023.0,N,Y,Y,2017,1,14,N,6.0
45,1629734,Kyle,Alexander,Kyle Alexander,"Alexander, Kyle",K. Alexander,kyle-alexander,1996-10-21 00:00:00,Tennessee,Canada,...,2019.0,2019.0,Y,Y,Y,Undrafted,Undrafted,Undrafted,N,0.0
74,1507,Derek,Anderson,Derek Anderson,"Anderson, Derek",D. Anderson,derek-anderson,1974-07-18 00:00:00,Kentucky,USA,...,1997.0,2007.0,N,Y,Y,1997,1,13,N,10.0
82,76041,Kim,Anderson,Kim Anderson,"Anderson, Kim",K. Anderson,kim-anderson,1955-05-12 00:00:00,Missouri,USA,...,1978.0,1978.0,N,Y,Y,1978,7,146,N,0.0
90,1000,Shandon,Anderson,Shandon Anderson,"Anderson, Shandon",S. Anderson,shandon-anderson,1973-12-31 00:00:00,Georgia,USA,...,1996.0,2005.0,N,Y,Y,1996,2,54,N,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4071,78582,Nikita,Wilson,Nikita Wilson,"Wilson, Nikita",N. Wilson,nikita-wilson,1964-02-25 00:00:00,Louisiana State,USA,...,1987.0,1987.0,N,Y,Y,1987,2,30,N,0.0
4090,78600,Brian,Winters,Brian Winters,"Winters, Brian",B. Winters,brian-winters,1952-03-01 00:00:00,South Carolina,USA,...,1974.0,1982.0,N,Y,Y,1974,1,12,N,8.0
4106,1630218,Robert,Woodard II,Robert Woodard II,"Woodard II, Robert",R. Woodard II,robert-woodard-ii,1999-09-22 00:00:00,Mississippi State,USA,...,2020.0,2021.0,Y,Y,Y,2020,2,40,N,1.0
4138,2428,Vincent,Yarbrough,Vincent Yarbrough,"Yarbrough, Vincent",V. Yarbrough,vincent-yarbrough,1981-03-21 00:00:00,Tennessee,USA,...,2002.0,2002.0,N,Y,Y,2002,2,32,N,0.0
4164,2583,Derrick,Zimmerman,Derrick Zimmerman,"Zimmerman, Derrick",D. Zimmerman,derrick-zimmerman,1981-12-02 00:00:00,Mississippi State,USA,...,2005.0,2005.0,Y,Y,Y,2003,2,40,N,0.0

In [246]:
print(sec_df["year_in_league"].mean())
print(sec_df["year_in_league"].median())
print(sec_df["year_in_league"].mode())

4.783068783068783
3.0
0    0.0
Name: year_in_league, dtype: float64

In [248]:
sec_df.loc[sec_df["school"] == "Mississippi"]

,person_id,first_name,last_name,display_first_last,display_last_comma_first,display_fi_last,player_slug,birthdate,school,country,...,from_year,to_year,dleague_flag,nba_flag,games_played_flag,draft_year,draft_round,draft_number,greatest_75_flag,year_in_league
876,1629056,Terence,Davis,Terence Davis,"Davis, Terence",T. Davis,terence-davis,1997-05-16 00:00:00,Mississippi,USA,...,2019.0,2023.0,N,Y,Y,Undrafted,Undrafted,Undrafted,N,4.0
1030,76635,Patrick,Eddie,Patrick Eddie,"Eddie, Patrick",P. Eddie,patrick-eddie,1967-12-27 00:00:00,Mississippi,USA,...,1991.0,1991.0,N,Y,Y,Undrafted,Undrafted,Undrafted,N,0.0
1324,76821,Gerald,Glass,Gerald Glass,"Glass, Gerald",G. Glass,gerald-glass,1967-11-12 00:00:00,Mississippi,USA,...,1990.0,1995.0,N,Y,Y,1990,1,20,N,5.0
2715,77705,Johnny,Neumann,Johnny Neumann,"Neumann, Johnny",J. Neumann,johnny-neumann,1951-09-11 00:00:00,Mississippi,USA,...,1976.0,1977.0,N,Y,Y,1973,6,98,N,1.0
3079,2770,Justin,Reed,Justin Reed,"Reed, Justin",J. Reed,justin-reed,1982-01-16 00:00:00,Mississippi,USA,...,2004.0,2006.0,Y,Y,Y,2004,2,40,N,2.0
3325,1738,Ansu,Sesay,Ansu Sesay,"Sesay, Ansu",A. Sesay,ansu-sesay,1976-07-29 00:00:00,Mississippi,USA,...,2001.0,2004.0,N,Y,Y,1998,2,30,N,3.0
3558,78274,John,Stroud,John Stroud,"Stroud, John",J. Stroud,john-stroud,1957-10-29 00:00:00,Mississippi,USA,...,1980.0,1980.0,N,Y,Y,1980,2,27,N,0.0
3736,78378,Elston,Turner,Elston Turner,"Turner, Elston",E. Turner,elston-turner,1959-06-10 00:00:00,Mississippi,USA,...,1981.0,1988.0,N,Y,Y,1981,2,43,N,7.0